apiVersion: v1
kind: Service
metadata:
  name: kubernetes-backend
spec:
  selector:
    app: kubernetes
  ports:
    - port: 80
      targetPort: 9090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubecontainer
        image: icarusblake/aibacetdev 
        ports:
          - containerPort: 9090
        env:
          - name: MONGO
            value: mongodb+srv://admmongo:Pa$$w0rd123.@ecommerce.4v4b28p.mongodb.net/?retryWrites=true&w=majority
          - name: JWT_KEY
            value: "SecretCoderKey"
          - name: JWT_RESET_PASSWORD_KEY
            value: "d942738b"
          - name: JWT_COOKIE_KEY
            value: "jwtCookieToken"
          - name: GITHUB_CLIENT_ID
            value: "Iv1.5f0457c348511f7e"
          - name: GITHUB_CLIENT_SECRET
            value: "bd54238664f4c40669fefd6b33243246f11af152"
          - name: GITHUB_CALLBACK_URL
            value: "http://localhost:8080/api/users/githubcallback"
          - name: ADMIN_EMAIL
            value: "aaron.ibaceta@hotmail.com"
          - name: ADMIN_PASSWORD
            value: "LOCOadmin123"
          - name: PERSISTENCE
            value: "MONGO"
          - name: NODEMAILER_GMAIL
            value: "snackimpact@gmail.com"
          - name: NODEMAILER_PASS
            value: "gcnszdyzmiaxbqzy"
        imagePullPolicy: Always
